/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  Notes: () => import('#controllers/notes_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Session: () => import('#controllers/session_controller'),
  TodoAuths: () => import('#controllers/todo_auths_controller'),
  Todos: () => import('#controllers/todos_controller'),
}
