/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class LabelSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = LabelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NoteLabelSchema extends BaseModel {
  static $columns = ['id', 'labelId', 'noteId'] as const
  $columns = NoteLabelSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare labelId: number | null
  @column()
  declare noteId: number | null
}

export class NoteSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'imageUrl', 'pinned', 'shareToken', 'title', 'updatedAt'] as const
  $columns = NoteSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imageUrl: string | null
  @column()
  declare pinned: boolean
  @column()
  declare shareToken: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'status', 'title', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TodoLabelSchema extends BaseModel {
  static $columns = ['id', 'labelId', 'todoId'] as const
  $columns = TodoLabelSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare labelId: number | null
  @column()
  declare todoId: number | null
}

export class TodoSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isCompleted', 'title', 'updatedAt'] as const
  $columns = TodoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCompleted: boolean
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
